//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskLogEntities : DbContext
    {
        public TaskLogEntities()
            : base("name=TaskLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblActivityLog> TblActivityLog { get; set; }
        public virtual DbSet<TblRoles> TblRoles { get; set; }
        public virtual DbSet<TblTaskByIndividual> TblTaskByIndividual { get; set; }
        public virtual DbSet<TblTaskBySuperior> TblTaskBySuperior { get; set; }
        public virtual DbSet<TblUsers> TblUsers { get; set; }
        public virtual DbSet<TblWorkOperational> TblWorkOperational { get; set; }
        public virtual DbSet<TblUserActivity> TblUserActivity { get; set; }
        public virtual DbSet<TblTasks> TblTasks { get; set; }
        public virtual DbSet<TblProjectSubmission> TblProjectSubmission { get; set; }
    }
}
