//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivityLog
    {
        public int Id { get; set; }
        public int ownerId { get; set; }
        public string ownerFullName { get; set; }
        public Nullable<int> activityDescription { get; set; }
        public Nullable<System.DateTime> dateRecorded { get; set; }
        public bool deleted { get; set; }
        public string deletedBy { get; set; }
    }
}
