//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInternalActivityOnly
    {
        public string code { get; set; }
        public string title { get; set; }
        public string reqDepartment { get; set; }
        public string requestor { get; set; }
        public string objective { get; set; }
        public string siteLoc { get; set; }
        public string status { get; set; }
        public string statusSummary { get; set; }
        public string priority { get; set; }
    }
}
