//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjectSubmission
    {
        public string unique_id { get; set; }
        public string project_title { get; set; }
        public string requesting_department { get; set; }
        public string project_initiator { get; set; }
        public string strategy_objective { get; set; }
        public string site_location { get; set; }
        public string problem_statement { get; set; }
        public string status { get; set; }
        public string status_summary { get; set; }
        public string priority { get; set; }
        public string cumulative_percentage { get; set; }
        public string budget_planned { get; set; }
        public string budget_actual { get; set; }
        public string budget_remaining { get; set; }
        public string budget_status { get; set; }
        public string otd { get; set; }
        public Nullable<System.DateTime> planned_start_date { get; set; }
        public Nullable<System.DateTime> planned_completion_date { get; set; }
        public Nullable<System.DateTime> actual_start_date { get; set; }
        public Nullable<System.DateTime> actual_completion_date { get; set; }
    }
}
