//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTasks
    {
        public int Id { get; set; }
        public string taskTitle { get; set; }
        public string taskDescription { get; set; }
        public bool isActive { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public string status { get; set; }
    }
}
