//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTaskByIndividual
    {
        public int Id { get; set; }
        public Nullable<int> IdTBS { get; set; }
        public int ownerId { get; set; }
        public string ownerBadgeId { get; set; }
        public string ownerFullName { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public string currentStatus { get; set; }
        public string remarks { get; set; }
        public string remarksWhenCanceled { get; set; }
        public string remarksWhenPaused { get; set; }
        public string attachment { get; set; }
        public bool canceled { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public string updateBy { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
        public string deletedBy { get; set; }
    }
}
