//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsers
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string badgeId { get; set; }
        public string fullName { get; set; }
        public string title { get; set; }
        public int levelPosition { get; set; }
        public Nullable<int> superiorId { get; set; }
    }
}
