//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserActivity
    {
        public int Id { get; set; }
        public string jobType { get; set; }
        public string badgeId { get; set; }
        public string fullName { get; set; }
        public string section { get; set; }
        public Nullable<System.DateTime> startDatetime { get; set; }
        public Nullable<System.DateTime> stopDatetime { get; set; }
        public Nullable<int> duration { get; set; }
        public string taskId { get; set; }
        public string taskTitle { get; set; }
        public string remarks { get; set; }
        public string activity { get; set; }
    }
}
