//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeClock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWorkOperational
    {
        public int Id { get; set; }
        public string planSites { get; set; }
        public string taskType { get; set; }
        public string issueDescription { get; set; }
        public string unitOrArea { get; set; }
        public Nullable<System.DateTime> reportedOn { get; set; }
        public Nullable<System.DateTime> requestedOn { get; set; }
        public string reportedBy { get; set; }
        public string reportedByDepartment { get; set; }
        public Nullable<System.DateTime> actionStart { get; set; }
        public Nullable<System.DateTime> actionFinish { get; set; }
        public Nullable<System.DateTime> actionFinishActual { get; set; }
        public Nullable<int> durationPlanned { get; set; }
        public Nullable<int> durationActual { get; set; }
        public string PIC { get; set; }
        public string PICworkers { get; set; }
        public string troubleshootResult { get; set; }
        public string rootCause { get; set; }
        public string correctiveAction { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public bool dlt { get; set; }
    }
}
